markdown: kramdown
sass:
  style: :compressed
exclude:
- README.md
- wp-content/README.md
- vendor
permalink: /:categories/:year/:month/:day/

title: Austin JavaScript

description: >
  Austin JavaScript is a meetup group focused on JavaScript and the open web.

twitter:
  user: AustinJS
  url: https://twitter.com/AustinJS

# people and organizational data is located in _data directory
